Http client discovery
http-interop/http-factory-discovery pull request #9
Opened 2018-12-06 11:44 UTC by Stadly

Make it possible to discover PSR-18 HTTP Client implementations.

Solves https://github.com/http-interop/http-factory-discovery/issues/6.

This pull request depends on https://github.com/http-interop/http-factory-discovery/pull/7 and https://github.com/http-interop/http-factory-discovery/pull/8.

There is currently only one HTTP Client implementation that works: `Http\Adapter\Guzzle6\Client`. But the following implementations will also start working when/if they are updated to support PSR-18:
- `Http\Adapter\Guzzle5\Client`
- `Http\Client\Curl\Client`
- `Http\Client\Socket\Client`
- `Http\Adapter\React\Client`
- `Http\Adapter\Buzz\Client`
- `Http\Adapter\Cake\Client`
- `Http\Adapter\Zend\Client`
- `Http\Adapter\Artax\Client`

2018-12-06 11:55 UTC, Stadly commented
I am not sure why the build fails on lower dependencies. What does the script `test-all` do? I can't find it anywhere.

2018-12-06 13:40 UTC, shadowhand commented
> What does the script `test-all` do? I can't find it anywhere.

https://github.com/http-interop/http-factory-discovery/blob/master/scripts/test-all

2018-12-06 13:46 UTC, shadowhand commented
Tests need to be fixed.

2018-12-06 13:46 UTC, shadowhand requested changes
Needs a rebase and test changes. Please use commit amending and force push so there is only one commit.

2018-12-06 14:01 UTC, shadowhand commented
Needs a rebase and test changes. Please use commit amending and force push so there is only one commit.

2018-12-06 15:02 UTC, Stadly commented
Haha! I've tried to do some rebasing and squashing, but that was not too successful, to say the least. Followed this guide: https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request Do you have any hints?

2018-12-06 15:12 UTC, shadowhand commented
Typically:

```sh
git rebase origin/master
# make changes
git commit --amend
git push --force-with-lease
```

Specifically for this branch:

```sh
git reset --hard origin/master
git cherry-pick abb08456fdd236f17b0bf9047c2ce28f48784563
git push --force-with-lease 
```

2018-12-06 15:12 UTC, shadowhand commented
Typically:

```sh
git rebase origin/master
# make changes, git add, etc
git commit --amend
git push --force-with-lease
```

Specifically for this branch:

```sh
git reset --hard origin/master
git cherry-pick abb08456fdd236f17b0bf9047c2ce28f48784563
git push --force-with-lease 
```

2018-12-06 15:46 UTC, Stadly commented
Do you have an idea what might be done about the tests?

2018-12-06 18:28 UTC, shadowhand commented
Not quite sure what to do about tests... Let me puzzle on that one.

2018-12-07 08:00 UTC, Stadly commented
I gave it a go :) What do you think?

2018-12-07 09:21 UTC, Stadly commented
Gave it a go :) What do you think?

2018-12-08 19:35 UTC, shadowhand approved these changes

2018-12-08 19:36 UTC, merged

2018-12-08 19:36 UTC, shadowhand commented
Thanks!

2018-12-08 19:40 UTC, shadowhand commented
Released in version 1.4.0.